name: Dr. Harry Stephan
favicon: null
layout_spectrum: 0.34859282174147666
typography_spectrum: 0.031077071325853467
title: Dr. Harry Stephan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.23201836785301566
  lightness: 0.1468216790817678
  saturation: 0.22967181913554668
  rhythmicContrast: 0.8108162707649171
purpose: []
