name: Dr. Harry Stephan
favicon: null
layout_spectrum: 0.74585
typography_spectrum: 1
title: Dr. Harry Stephan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 1
purpose: []
